image: python:3-alpine

stages:
  - test
  - build
  - deploy

before_script:
  # Alpine needs some deps to run scipy's FORTRAN code.
  - apk --no-cache add lapack libstdc++
  - apk --no-cache add --virtual .builddeps g++ gcc gfortran musl-dev lapack-dev
  - pip install twine tox setuptools wheel

pytest-py37:
  stage: test
  script:
    - tox -e py37

linters:
  stage: test
  script:
    - tox -e linters

build-staging:
  stage: build
  script: tox -e build
  artifacts:
    paths:
      - dist/
    expire_in: 1 month
  except:
    - tags

deploy-staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASS
  script:
    - twine upload --skip-existing --verbose --repository-url https://test.pypi.org/legacy/ dist/*
  except:
    - tags

build-release:
  stage: build
  script: tox -e build
  artifacts:
    paths:
      - dist/
  only:
    - tags

deploy-release:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASS
  script:
    - twine upload --skip-existing --verbose --repository-url https://upload.pypi.org/legacy/  dist/*
  only:
    - tags
