image: python:3-slim

stages:
  - test
  - build
  - deploy

before_script:
  - pip install twine tox setuptools wheel

pytest-py37:
  stage: test
  script:
    - tox -e py37

# Pylint is hella slow, so it gets its own pipeline.
linters-nopylint:
  stage: test
  script:
    - tox -e linters-nopylint

linters-pylint:
  stage: test
  script:
    - tox -e pylint

build-staging:
  stage: build
  image: python:alpine
  script: tox -e build
  artifacts:
    paths:
      - dist/
    expire_in: 1 month
