image: python:3-slim

stages:
  - test
  - build
  - deploy

before_script:
  - pip install twine tox setuptools wheel

pytest-py37:
  stage: test
  script:
    - tox -e py37

#linters:
#  stage: test
#  script:
#    - tox -e linters

build-staging:
  stage: build
  script: tox -e build
  artifacts:
    paths:
      - dist/
    expire_in: 1 month
  except:
    - tags

deploy-staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ -u Seirdy dist/*
  except:
    - tags

build-release:
  stage: build
  script: tox -e build
  artifacts:
    paths:
      - dist/
  only:
    - tags

deploy-release:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASS
  script:
    - twine upload --skip-existing --verbose --repository-url https://upload.pypi.org/legacy/  dist/*
  only:
    - tags
