image: python:latest

stages:
  - test
  - build
  - deploy

before_script:
  - pip install twine tox setuptools wheel

pytest-py37:
  stage: test
  script:
    - tox -e py37

linters:
  stage: test
  script:
    - tox -e linters

build:
  stage: build
  script: tox -e build
  artifacts:
    paths:
      - dist/
    expire_in: 1 month

deploy-staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASS
  script:
    - twine upload --skip-existing --verbose --repository-url https://test.pypi.org/legacy/ dist/*
  except:
    - tags

deploy-production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASS
  script:
    - twine upload --skip-existing --verbose --repository-url https://upload.pypi.org/legacy/ --username=$PYPI_USER --password=$PYPI_PASS dist/*
  only:
    - tags
