image: python:latest

stages:
- test
- build

before_script:
  - pip install tox pytest numpy scipy mpmath pandas mypy pytest-mypy pytest-cov pytest-pylint

pytest-py37:
  stage: test
  script:
  - tox -e py37

linters:
  stage: test
  script:
  - tox -e linters

build:
  stage: build
  script: tox -e build
  artifacts:
    paths:
    - dist/
    expire_in: 1 month
