image: python:latest

stages:
- test
- build
- deploy

before_script:
  - pip install twine tox

pytest-py37:
  stage: test
  script:
  - tox -e py37

linters:
  stage: test
  script:
  - tox -e linters

build:
  stage: build
  script: tox -e build
  artifacts:
    paths:
    - dist/
    expire_in: 1 month

deploy_staging:
  stage: deploy
  variables:
    TWINE_USER: $PYPI_USER
    TWINE_PASS: $PYPI_PASS
  script:
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USER: $PYPI_USER
    TWINE_PASS: $PYPI_PASS
  script:
    - twine upload dist/*
  only:
    - tags