image: python:3-slim

stages:
  - test
  - build

before_script:
  - pip install tox

pytest-py37:
  stage: test
  script:
    - tox -e py37

# Pylint is hella slow, so it gets its own pipeline.
linting 1/4:
  stage: test
  image: python:alpine
  script:
    - tox -e pydocstyle,pyroma

linting 2/4:
  stage: test
  image: python:3-slim
  script:
    - tox -e mypy

linting 3/4:
  stage: test
  image: python:3-slim
  script:
    tox -e flake8

linting 4/4:
  stage: test
  image: python:alpine
  script:
    - tox -e pylint

build-test:
  stage: build
  image: python:alpine
  script: tox -e build
  except:
    refs:
      - master

build-staging:
  stage: build
  image: python:alpine
  script: tox -e build
  artifacts:
    paths:
      - dist/
    expire_in: 1 month
  only:
    refs:
      - master
  except:
    - tags

build-release:
  stage: build
  image: python:alpine
  script: tox -e build
  artifacts:
    paths:
      - dist/
  only:
    - tags
