name: func-analysis
channels:
  - conda-forge
  - defaults
  - pypi
dependencies:
  - python>=3.7.2
  - pip
  - numpy
  - scipy
  - mpmath
  - pytest>=4.0.1
  - pytest-cov
  - black
  - isort
  - mypy
  - flake8
  - pep8-naming
  - flake8-blind-except
  - flake8-builtins
  - flake8-comprehensions
  - flake8-mutable
  - flake8-pep3101
  - flake8-polyfill
  - flake8-self
  - pylint
  - pydocstyle
  - pyroma
  - wheel
  - setuptools
  - twine
  - xenon
  - python-language-server>=0.22.0
  - pip:
      - cohesion
      - hacking
      - pydiatra
      - flake8-eradicate
      - flake8-tuple
      - flake8-super-call
      - flake8-colors
      - flake8-per-file-ignores
      - flake8-bugbear
      - flake8-deprecated
      - pytest-sugar>=0.9.2
      - flake8-bandit
      - flake8-pytest
      - flake8-isort
      - flake8-tidy-imports
      - wemake-python-styleguide>=0.7.1
      - yesqa
      - pyls-isort
      - pyls-black
      - pyls-mypy
      - tox>=3.7.0
