[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=79
known_future_library="annotations"


[tool.black]
line-length = 79
py36 = true
quiet = true
